feat: add custom header to date picker and bump versions
indec-it/react-commons pull request #100
Opened 2023-02-03 16:09 UTC by arielerv

# Description

Add a custom header on date picker

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How to test

you should pass a flag isCustomHeader in true on the DatePicker.stories to test it.

2023-02-07 10:54 UTC, maximilianoforlenza commented
Pongo el PR como draft, cuando este listo para revisar ponelo como "ready for review"

2023-02-08 10:40 UTC, maximilianoforlenza requested changes

2023-02-08 10:40 UTC, maximilianoforlenza commented on src/components/DatePicker/DatePicker.test.js
> +            expect(props.onChange).toHaveBeenCalledTimes(0);
por que este onChange ya no se llamaria?

2023-02-08 10:40 UTC, maximilianoforlenza commented on src/components/SelectInput/MenuList/MenuList.test.js
> -    describe('when `hasMore` is defined', () => {
no deberias borrar el test deberias modificarlo, es decir si por algun motivo cuando la prop hasMore es true ya no tinee que mostrar ese menu list deberias en lugar de usar un `getByTestId` un `queryByTestId` y el `toBeInTheDocument` por un `toBeNull` y cambiar el test diciendo `should not display a menu list footer`

2023-02-08 10:40 UTC, maximilianoforlenza commented on src/components/DatePicker/DatePickerHeader/index.js
> +import React from 'react';
En todos los componentes se crea un archivo con el mismo nombre del componente y un index para exportarlo. este es diferente y queda mal, o modificas todos los componentes o a este le agregas otro archivo para el componente

2023-02-08 10:40 UTC, maximilianoforlenza commented on src/components/DatePicker/DatePickerHeader/index.js
> +const DatePickerHeader = ({
Falta el test, pero lo podes dejar para otro PR

2023-02-08 10:42 UTC, maximilianoforlenza commented on src/components/DatePicker/DatePicker.test.js
> +            expect(props.onChange).toHaveBeenCalledTimes(0);
Si una prop hace que el onChange se ejecute y otra prop hace que se ejecute otra fn deberias testearlo

2023-02-08 10:48 UTC, maximilianoforlenza commented on src/components/DatePicker/DatePicker.test.js
> +            it('should display a custom header', async () => {
por que es async esto?

2023-02-08 22:06 UTC, arielerv commented on src/components/DatePicker/DatePicker.test.js
> +            expect(props.onChange).toHaveBeenCalledTimes(0);
cambió en la libreria. Ahora manda el onChangeRaw, por el customInput.

2023-02-08 23:02 UTC, arielerv commented on src/components/SelectInput/MenuList/MenuList.test.js
> -    describe('when `hasMore` is defined', () => {
ya no renderiza el footer si no lo muestra, pero lo agrego al SelectInput.test.js.

2023-02-08 23:17 UTC, arielerv commented on src/components/DatePicker/DatePickerHeader/index.js
> +const DatePickerHeader = ({
agrego los de render.

2023-02-09 09:44 UTC, maximilianoforlenza approved these changes

2023-02-09 09:45 UTC, merged